# Generated by Django 4.1.4 on 2023-01-16 16:56

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_user.png', null=True, upload_to=account.models.upload_location),
        ),
    ]
