# Generated by Django 4.1.4 on 2023-02-20 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
