# Generated by Django 4.1.4 on 2023-02-19 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import program.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('session', models.CharField(default='2022/2023', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(upload_to='upload/')),
                ('file2', models.FileField(upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_program_type', to='program.program_type')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_program_type', to='program.program_type')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('payment_reference', models.CharField(blank=True, default='0', max_length=25)),
                ('payment', models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=25)),
                ('reference_number', models.CharField(max_length=30)),
                ('reference_url', models.CharField(max_length=255)),
                ('application_id', models.CharField(max_length=26, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('other_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Select', 'Select'), ('Male', 'Male'), ('Female', 'Female')], default='select', max_length=20)),
                ('marital_status', models.CharField(choices=[('Select', 'Select'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='select', max_length=20)),
                ('disability', models.CharField(choices=[('Select', 'Select'), ('No', 'No'), ('Yes', 'Yes')], default='select', max_length=20)),
                ('disability_type', models.CharField(blank=True, max_length=100, null=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=20, null=True)),
                ('previous_ijmb_number', models.CharField(blank=True, max_length=10, null=True)),
                ('id_type', models.CharField(choices=[('Select', 'Select'), ('National ID', 'National Id'), ('International Passport', 'International Passport')], default='select', max_length=25)),
                ('id_number', models.CharField(blank=True, max_length=12, null=True)),
                ('id_issued', models.DateField(blank=True, null=True)),
                ('id_expiry', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('postal', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('lga', models.CharField(blank=True, max_length=30, null=True)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('next_of_kin_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=14, null=True)),
                ('next_of_kin_address', models.CharField(blank=True, max_length=250, null=True)),
                ('next_of_kin_relationship', models.CharField(choices=[('Select', 'Select'), ('Sibling', 'Parent'), ('Parent', 'Sibling'), ('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Other', 'Other')], default='Select', max_length=20)),
                ('next_of_kin_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('next_of_kin_occupation_address', models.CharField(blank=True, max_length=250, null=True)),
                ('file_photo_passport', models.FileField(blank=True, null=True, upload_to=program.models.upload_location)),
                ('file_identification', models.FileField(blank=True, null=True, upload_to=program.models.upload_location)),
                ('file_first_certificate', models.FileField(blank=True, null=True, upload_to=program.models.upload_location)),
                ('file_first_testimonial', models.FileField(blank=True, null=True, upload_to=program.models.upload_location)),
                ('file_second_certificate', models.FileField(blank=True, null=True, upload_to=program.models.upload_location)),
                ('file_second_testimonial', models.FileField(blank=True, null=True, upload_to=program.models.upload_location)),
                ('file_awaiting_exam_slip', models.FileField(blank=True, null=True, upload_to=program.models.upload_location)),
                ('file_scratch_card', models.FileField(blank=True, null=True, upload_to=program.models.upload_location)),
                ('post_type', models.CharField(blank=True, default='program', max_length=30, null=True)),
                ('submitted', models.DateTimeField(blank=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.course')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.faculty')),
                ('p_subject1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject1', to='program.subject')),
                ('p_subject2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject2', to='program.subject')),
                ('p_subject3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject3', to='program.subject')),
                ('p_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.program_type')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.session')),
                ('status', models.ForeignKey(blank=True, default=9, on_delete=django.db.models.deletion.DO_NOTHING, to='program.status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Olevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_level_status', models.CharField(choices=[('Select', 'Select'), ('One Sitting', 'One Sitting'), ('Two Sitting', 'Two Sitting')], default='Select', max_length=20)),
                ('examination_type', models.CharField(choices=[('Select', 'Select'), ('WAEC', 'Waec'), ('NECO', 'Neco'), ('NAPTEB', 'Napteb')], default='Select', max_length=20)),
                ('examination_center', models.CharField(blank=True, max_length=200, null=True)),
                ('examination_number', models.CharField(blank=True, max_length=15, null=True)),
                ('examination_year', models.CharField(blank=True, max_length=4, null=True)),
                ('grade1', models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade1', to='program.grade')),
                ('grade2', models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade2', to='program.grade')),
                ('grade3', models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade3', to='program.grade')),
                ('grade4', models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade4', to='program.grade')),
                ('grade5', models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade5', to='program.grade')),
                ('grade6', models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade6', to='program.grade')),
                ('grade7', models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade7', to='program.grade')),
                ('grade8', models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade8', to='program.grade')),
                ('grade9', models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade9', to='program.grade')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.registration')),
                ('subject1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject1', to='program.subject')),
                ('subject2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject2', to='program.subject')),
                ('subject3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject3', to='program.subject')),
                ('subject4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject4', to='program.subject')),
                ('subject5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject5', to='program.subject')),
                ('subject6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject6', to='program.subject')),
                ('subject7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject7', to='program.subject')),
                ('subject8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject8', to='program.subject')),
                ('subject9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject9', to='program.subject')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='program_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade_program_type', to='program.program_type'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='program_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='faculty_program_type', to='program.program_type'),
        ),
        migrations.AddField(
            model_name='course',
            name='combination',
            field=models.ManyToManyField(blank=True, related_name='combination', to='program.subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='others',
            field=models.ManyToManyField(blank=True, related_name='others', to='program.subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='program_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_program_type', to='program.program_type'),
        ),
    ]
