# Generated by Django 4.1.4 on 2023-01-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='Course',
        ),
    ]
