# Generated by Django 4.1.4 on 2023-02-20 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olevel',
            name='grade1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade1', to='program.grade'),
        ),
        migrations.AlterField(
            model_name='olevel',
            name='grade2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade2', to='program.grade'),
        ),
        migrations.AlterField(
            model_name='olevel',
            name='grade3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade3', to='program.grade'),
        ),
        migrations.AlterField(
            model_name='olevel',
            name='grade4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade4', to='program.grade'),
        ),
        migrations.AlterField(
            model_name='olevel',
            name='grade5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade5', to='program.grade'),
        ),
        migrations.AlterField(
            model_name='olevel',
            name='grade6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade6', to='program.grade'),
        ),
        migrations.AlterField(
            model_name='olevel',
            name='grade7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade7', to='program.grade'),
        ),
        migrations.AlterField(
            model_name='olevel',
            name='grade8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade8', to='program.grade'),
        ),
        migrations.AlterField(
            model_name='olevel',
            name='grade9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade9', to='program.grade'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.status'),
        ),
    ]
