# Generated by Django 4.1.4 on 2023-02-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_olevel_grade1_alter_olevel_grade2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
