# Generated by Django 4.1.4 on 2023-01-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_remove_course_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='program_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
