# Generated by Django 4.1.4 on 2023-01-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_subject_program_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='program_id',
        ),
    ]
