# Generated by Django 4.1.4 on 2023-01-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='combination',
            field=models.ManyToManyField(to='program.subject'),
        ),
    ]
