# Generated by Django 4.1.4 on 2023-01-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_course_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='others',
            field=models.ManyToManyField(related_name='others', to='program.subject'),
        ),
        migrations.AlterField(
            model_name='course',
            name='combination',
            field=models.ManyToManyField(limit_choices_to=4, related_name='combination', to='program.subject'),
        ),
    ]
