# Generated by Django 4.1.4 on 2023-01-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_course_others_alter_course_combination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='combination',
            field=models.ManyToManyField(related_name='combination', to='program.subject'),
        ),
    ]
