# Generated by Django 4.1.4 on 2023-01-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_alter_course_combination_alter_course_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_program_type', to='program.program_type'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='program_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_program_type', to='program.program_type'),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='faculty_program_type', to='program.program_type')),
            ],
        ),
    ]
