# Generated by Django 4.1.4 on 2023-01-16 17:15

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0016_course_created_course_updated_faculty_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='application_id',
            field=models.CharField(blank=True, max_length=26, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.course'),
        ),
        migrations.AddField(
            model_name='registration',
            name='disability',
            field=models.CharField(choices=[('Select', 'Select'), ('No', 'No'), ('Yes', 'Yes')], default='Select', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='disability_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.faculty'),
        ),
        migrations.AddField(
            model_name='registration',
            name='file_awaiting_exam_slip',
            field=models.FileField(blank=True, null=True, upload_to=account.models.upload_location),
        ),
        migrations.AddField(
            model_name='registration',
            name='file_first_certificate',
            field=models.FileField(blank=True, null=True, upload_to=account.models.upload_location),
        ),
        migrations.AddField(
            model_name='registration',
            name='file_first_testimonial',
            field=models.FileField(blank=True, null=True, upload_to=account.models.upload_location),
        ),
        migrations.AddField(
            model_name='registration',
            name='file_identification',
            field=models.FileField(blank=True, null=True, upload_to=account.models.upload_location),
        ),
        migrations.AddField(
            model_name='registration',
            name='file_photo_passport',
            field=models.FileField(blank=True, null=True, upload_to=account.models.upload_location),
        ),
        migrations.AddField(
            model_name='registration',
            name='file_scratch_card',
            field=models.FileField(blank=True, null=True, upload_to=account.models.upload_location),
        ),
        migrations.AddField(
            model_name='registration',
            name='file_second_certificate',
            field=models.FileField(blank=True, null=True, upload_to=account.models.upload_location),
        ),
        migrations.AddField(
            model_name='registration',
            name='file_second_testimonial',
            field=models.FileField(blank=True, null=True, upload_to=account.models.upload_location),
        ),
        migrations.AddField(
            model_name='registration',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('Select', 'Select'), ('Male', 'Male'), ('Female', 'Female')], default='Select', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='id_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='id_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='id_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='id_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='lga',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='marital_status',
            field=models.CharField(choices=[('Select', 'Select'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='Select', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='next_of_kin_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='next_of_kin_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='next_of_kin_occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='next_of_kin_occupation_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='next_of_kin_relationship',
            field=models.CharField(choices=[('Select', 'Select'), ('Sibling', 'Parent'), ('Parent', 'Sibling'), ('Uncle', 'Uncle')], default='Select', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='other_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='p_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.program_type'),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='postal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='previous_ijmb_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.session'),
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='subject1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject1', to='program.subject'),
        ),
        migrations.AddField(
            model_name='registration',
            name='subject2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject2', to='program.subject'),
        ),
        migrations.AddField(
            model_name='registration',
            name='subject3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject3', to='program.subject'),
        ),
    ]
