# Generated by Django 4.1.4 on 2023-01-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0017_registration_address_registration_application_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_level_status', models.CharField(choices=[('Select', 'Select'), ('One Sitting', 'One Sitting'), ('Two Sititng', 'Two Sitting'), ('Awaiting Result', 'Awaiting Result')], default='Select', max_length=20)),
                ('examination_type', models.CharField(choices=[('Select', 'Select'), ('WAEC', 'Waec'), ('NECO', 'Neco'), ('NAPTEB', 'Napteb')], default='Select', max_length=20)),
                ('examination_center', models.CharField(blank=True, max_length=200, null=True)),
                ('examination_number', models.CharField(blank=True, max_length=15, null=True)),
                ('examination_year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='combination',
            field=models.ManyToManyField(blank=True, null=True, related_name='combination', to='program.subject'),
        ),
        migrations.AlterField(
            model_name='course',
            name='others',
            field=models.ManyToManyField(blank=True, null=True, related_name='others', to='program.subject'),
        ),
    ]
