# Generated by Django 4.1.4 on 2023-01-16 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0018_olevel_alter_course_combination_alter_course_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='olevel',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.session'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='subject1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject1', to='program.subject'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='subject2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject2', to='program.subject'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='subject3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject3', to='program.subject'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='subject4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject4', to='program.subject'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='subject5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject5', to='program.subject'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='subject6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject6', to='program.subject'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='subject7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject7', to='program.subject'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='subject8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject8', to='program.subject'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='subject9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_subject9', to='program.subject'),
        ),
    ]
