# Generated by Django 4.1.4 on 2023-01-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0019_olevel_registration_olevel_subject1_olevel_subject2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olevel',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.registration'),
        ),
    ]
