# Generated by Django 4.1.4 on 2023-01-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0022_registration_next_of_kin_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='session',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
