# Generated by Django 4.1.4 on 2023-01-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0023_alter_registration_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='id',
        ),
        migrations.AlterField(
            model_name='registration',
            name='application_id',
            field=models.CharField(default=None, max_length=26, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
