# Generated by Django 4.1.4 on 2023-01-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0024_remove_registration_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='disability',
            field=models.CharField(choices=[('Select', 'Select'), ('No', 'No'), ('Yes', 'Yes')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('Select', 'Select'), ('Male', 'Male'), ('Female', 'Female')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id_type',
            field=models.IntegerField(choices=[('Select', 'Select'), ('National ID', 'National Id'), ('International Passport', 'International Passport')], default='select', max_length=25),
        ),
        migrations.AlterField(
            model_name='registration',
            name='marital_status',
            field=models.CharField(choices=[('Select', 'Select'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='select', max_length=20),
        ),
    ]
