# Generated by Django 4.1.4 on 2023-01-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0025_alter_registration_disability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id_type',
            field=models.CharField(choices=[('Select', 'Select'), ('National ID', 'National Id'), ('International Passport', 'International Passport')], default='select', max_length=25),
        ),
        migrations.AlterField(
            model_name='registration',
            name='next_of_kin_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='next_of_kin_relationship',
            field=models.CharField(choices=[('Select', 'Select'), ('Sibling', 'Parent'), ('Parent', 'Sibling'), ('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Other', 'Other')], default='Select', max_length=20),
        ),
    ]
