# Generated by Django 4.1.4 on 2023-01-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0026_alter_registration_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(default='2022/2023', max_length=15),
        ),
    ]
