# Generated by Django 4.1.4 on 2023-01-18 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0027_alter_session_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='next_of_kin_occupation_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade_program_type', to='program.program_type')),
            ],
        ),
        migrations.AddField(
            model_name='olevel',
            name='grade1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade1', to='program.grade'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='grade2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade2', to='program.grade'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='grade3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade3', to='program.grade'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='grade4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade4', to='program.grade'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='grade5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade5', to='program.grade'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='grade6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade6', to='program.grade'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='grade7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade7', to='program.grade'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='grade8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade8', to='program.grade'),
        ),
        migrations.AddField(
            model_name='olevel',
            name='grade9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_grade9', to='program.grade'),
        ),
    ]
