# Generated by Django 4.1.4 on 2023-01-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0028_alter_registration_next_of_kin_occupation_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olevel',
            name='o_level_status',
            field=models.CharField(choices=[('Select', 'Select'), ('One Sitting', 'One Sitting'), ('Two Sitting', 'Two Sitting'), ('Awaiting Result', 'Awaiting Result')], default='Select', max_length=20),
        ),
    ]
