# Generated by Django 4.1.4 on 2023-01-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0030_rename_subject1_registration_p_subject1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='session',
            field=models.CharField(blank=True, default=None, max_length=5),
            preserve_default=False,
        ),
    ]
