# Generated by Django 4.1.4 on 2023-01-20 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0031_alter_registration_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.session'),
        ),
    ]
