# Generated by Django 4.1.4 on 2023-01-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0032_alter_registration_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olevel',
            name='registration',
        ),
        migrations.AlterField(
            model_name='olevel',
            name='o_level_status',
            field=models.CharField(choices=[('Select', 'Select'), ('One Sitting', 'One Sitting'), ('Two Sitting', 'Two Sitting')], default='Select', max_length=20),
        ),
    ]
