# Generated by Django 4.1.4 on 2023-01-21 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0033_remove_olevel_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olevel',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.registration'),
        ),
    ]
