# Generated by Django 4.1.4 on 2023-01-21 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0034_olevel_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_program_type', to='program.program_type')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.status'),
        ),
    ]
