# Generated by Django 4.1.4 on 2023-01-21 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0035_status_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.ForeignKey(blank=True, default=9, on_delete=django.db.models.deletion.DO_NOTHING, to='program.status'),
        ),
    ]
