# Generated by Django 4.1.4 on 2023-01-21 14:46

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0036_alter_registration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(upload_to=account.models.upload_location)),
                ('file2', models.FileField(upload_to=account.models.upload_location)),
            ],
        ),
    ]
