# Generated by Django 4.1.4 on 2023-01-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0037_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file1',
            field=models.FileField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file2',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
