# Generated by Django 4.1.4 on 2023-01-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0038_alter_upload_file1_alter_upload_file2'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='post_type',
            field=models.CharField(blank=True, default='program', max_length=30, null=True),
        ),
    ]
