# Generated by Django 4.1.4 on 2023-01-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0039_registration_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_reference',
            field=models.CharField(blank=True, default='0', max_length=25),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=25),
        ),
    ]
